
import './styles/main.scss'
import './js/navbar/navbar.js'
import './js/sliders/interaction-slider.js'
import './js/animations/home.js'
import './js/animations/about.js'
import './js/animations/contact.js'
import './js/acorddions/questionsAnswer.js'
import './js/forms/contact-form.js'
import './js/animations/services.js'
import './js/utilities/upToTop.js'
